seed: 12345
output_folder: "./delme"
backend_name: null
is_backend_fake: True
problem_class: "SimpleProductionPlanningProblem"
circuit_class: "QAOACircuit"
num_layers: 3
num_starting_points: 1
lower_bound: 0.0
upper_bound: 3.15
optimization_params:
  optimizer: "SPSA"
  tolerance: 0.01
  maxiter: 30
  learning_rate: 0.8
  perturbation: 0.3
use_cache: False
cache_filename: "delme/cache.yaml"
cache_save_every: 1
num_estimator_shots: 10000
num_sampler_shots: 100000
problem_params:
  num_products: 4
  num_machines: 2

